// The text behind Settings, Report a problem: the route gathers the facts, this module turns them
// into lines and redacts the whole text, so one tested function owns what may leave the box.
const isJsonObject = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
/** The `version` of a parsed package.json, or null; lives here because adapter.ts may not typeof. */
export function versionOf(pkg) {
    if (!isJsonObject(pkg))
        return null;
    return typeof pkg.version === "string" ? pkg.version : null;
}
/** A private value is data, not a pattern: metacharacters in it must not reach the regex. */
function escapeRe(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
export function redact(text, p, keepHost) {
    let out = text;
    // 1. home path and file:// form to ~, both bare and prefixed.
    if (p.home.length > 0) {
        // Only at a path boundary: `/home/alice2/x` is another user's directory, not `~2/x`.
        const escaped = `${escapeRe(p.home)}(?=/|$|\\s|["'])`;
        out = out.replaceAll(new RegExp(`file://${escaped}`, "g"), "file://~");
        out = out.replaceAll(new RegExp(escaped, "g"), "~");
    }
    // 2. Every email address to <email>.
    out = out.replaceAll(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g, "<email>");
    // 3. Username as a whole word when long enough to avoid false positives on short substrings.
    if (p.user.length >= 3) {
        out = out.replaceAll(new RegExp(`\\b${escapeRe(p.user)}\\b`, "g"), "<user>");
    }
    // 4. Hostname as a whole word when not kept explicitly.
    if (p.hostname.length > 0 && !keepHost) {
        out = out.replaceAll(new RegExp(`\\b${escapeRe(p.hostname)}\\b`, "g"), "<host>");
    }
    // 5. Anthropic-style tokens and Bearer headers.
    out = out.replaceAll(/sk-ant-[A-Za-z0-9_-]{8,}/g, "<token>");
    out = out.replaceAll(/Bearer\s+[A-Za-z0-9._-]{16,}/g, "Bearer <token>");
    return out;
}
export function buildReport(input, p, keepHost) {
    const lines = [];
    lines.push(`dsh-oh-my-claude ${input.plugin}`);
    lines.push(`dsh: ${input.dsh ?? "unknown"}`);
    lines.push(`Claude Code: ${input.cli ?? "not found"} (${input.binary ? "on PATH" : "not on PATH"})`);
    lines.push(`OS: ${input.os}`);
    lines.push(`Node: ${input.node}`);
    const login = input.loggedIn ? "logged in" : "not logged in";
    const authSuffix = typeof input.authMethod === "string" && input.authMethod.length > 0
        ? ` · ${input.authMethod}`
        : "";
    lines.push(`Login: ${login}${authSuffix}`);
    lines.push(`Config dir: ${input.configDir}`);
    lines.push(`State dir: ${input.stateDir} (${input.stateWritable ? "writable" : "not writable"})`);
    if (keepHost)
        lines.push(`Host: ${p.hostname}`);
    lines.push(`Running sessions: ${input.running}`);
    if (input.mcp === null)
        lines.push("MCP: n/a (no running session)");
    else if (input.mcp.length === 0)
        lines.push("MCP: none");
    else
        lines.push(`MCP: ${input.mcp.map((s) => `${s.name}=${s.status}`).join(", ")}`);
    const lastError = input.lastError?.trim();
    lines.push(`Last error: ${lastError ?? "none"}`);
    const keys = Object.keys(input.switches).toSorted();
    if (keys.length === 0)
        lines.push("Switches: none");
    else
        lines.push(`Switches: ${keys.map((k) => `${k}=${input.switches[k]}`).join(", ")}`);
    lines.push("");
    lines.push("Generated by dsh-oh-my-claude; edit before sending.");
    return redact(lines.join("\n") + "\n", p, keepHost);
}
//# sourceMappingURL=report.js.map