// Offline self-check: bun src/report.test.ts. No I/O, pure functions only.
import assert from "node:assert/strict";
import { buildReport, redact, type PrivateValues } from "./report.js";

const priv: PrivateValues = {
  home: "/home/alice",
  user: "alice",
  hostname: "box7",
  email: "alice@example.com",
};

const input = {
  plugin: "1.0.0",
  dsh: "0.1.5-rc.2",
  cli: "2.1.268",
  binary: true,
  os: "linux 6.8.0",
  node: "bun 1.3.0",
  loggedIn: true,
  authMethod: "claude.ai",
  configDir: "/home/alice/.claude",
  stateDir: "/home/alice/.local/state/dsh-oh-my-claude",
  stateWritable: true,
  mcp: [{ name: "alice-tools", status: "connected" }],
  lastError: "token sk-ant-abcdefghijk for alice@example.com on box7",
  switches: { updateCheckOff: true, spendWarnUsd: 5 },
  running: 2,
};

const text = buildReport(input, priv, false);

// Config dir redacted; state dir home prefix redacted.
assert.ok(text.includes("Config dir: ~/.claude"), "config dir must show ~");
assert.ok(
  text.includes("State dir: ~/.local/state/dsh-oh-my-claude (writable)"),
  "state dir home prefix must be redacted",
);

// Private values gone.
assert.ok(!text.includes("alice@example.com"), "email must not appear");
assert.ok(!text.includes("/home/alice"), "home path must not appear");
assert.ok(!text.includes("sk-ant-abcdefghijk"), "token must not appear");

// Host redacted when keepHost is false.
assert.ok(!text.includes("box7"), "hostname must be redacted when keepHost=false");
assert.ok(!text.startsWith("Host:"), "no Host: line when keepHost=false");

// Host shown when keepHost is true.
const textWithHost = buildReport(input, priv, true);
assert.ok(textWithHost.includes("Host: box7"), "Host: line must appear when keepHost=true");

// Switches sorted by key.
const switchLine = text.split("\n").find((l) => l.startsWith("Switches:"));
assert.equal(switchLine, "Switches: spendWarnUsd=5, updateCheckOff=true", "switches sorted");

// MCP with user name redacted.
const mcpLine = text.split("\n").find((l) => l.startsWith("MCP:"));
assert.equal(mcpLine, "MCP: <user>-tools=connected", "MCP server name redacted");

// Login line.
const loginLine = text.split("\n").find((l) => l.startsWith("Login:"));
assert.equal(loginLine, "Login: logged in · claude.ai", "login with auth method");

// MCP null and empty cases.
assert.ok(
  buildReport({ ...input, mcp: null }, priv, false).includes("MCP: n/a (no running session)"),
  "null MCP shows n/a",
);
assert.ok(
  buildReport({ ...input, mcp: [] }, priv, false).includes("MCP: none"),
  "empty MCP shows none",
);

// Final non-empty line.
const nonEmpty = text.split("\n").filter((l) => l.length > 0);
assert.equal(
  nonEmpty[nonEmpty.length - 1],
  "Generated by dsh-oh-my-claude; edit before sending.",
  "final line",
);

// redact alone: Bearer token.
assert.equal(redact("Bearer abcdefghijklmnopqrstuvwxyz", priv, false), "Bearer <token>");

// redact alone: short user left alone.
const shortPriv: PrivateValues = { home: "/home/alice", user: "al", hostname: "box7" };
assert.ok(redact("al is here", shortPriv, false).includes("al"), "short user not redacted");

// A sibling directory that starts with the home path is not the home path.
assert.equal(
  redact("/home/alice2/config and /home/alice", priv, false),
  "/home/alice2/config and ~",
  "path boundary",
);

// file:// home redaction.
assert.equal(
  redact("file:///home/alice/x", priv, false),
  "file://~/x",
  "file:// home form redacted",
);

console.log("report ok");
